sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xsj

dir:
  upload: D:/Code/sky-take-out/resource/upload/
